export default {
  errors: true,
  errorDetails: true,
  colors: true,
  warnings: true,
  assets: false,
  cached: false,
  cachedAssets: false,
  children: false,
  chunks: false,
  chunkModules: false,
  chunkOrigins: false,
  depth: false,
  entrypoints: false,
  hash: false,
  maxModules: 1,
  modules: false,
  performance: false,
  providedExports: false,
  publicPath: false,
  reasons: false,
  source: false,
  timings: true,
  usedExports: false,
  version: false
}
